# Generated by Django 4.1.5 on 2023-01-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chibi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="slug_id",
        ),
        migrations.AddField(
            model_name="url",
            name="is_custom_slug",
            field=models.BooleanField(default=True),
        ),
    ]
